# Generated by Django 5.0.6 on 2024-07-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='StudentComplain',
        ),
    ]
